name: CMake

on:
  push:
    branches: [ main , ajian , Raja  ]
  pull_request:
    branches: [ main ]

jobs:
  linux_job:
    runs-on:  ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cmake 
        run:  mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build && cmake $GITHUB_WORKSPACE  --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug 
        shell: bash
      - name: make
        run: cd $GITHUB_WORKSPACE/build && make
        shell: bash
      - uses: purduesigbots/clang-format-action@1
        # use one of clang-format's supported styles or leave this out to use the style in your .clang-format file
        with:
          style: file
      # commit the changes (if there are any)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 🎨 apply clang-format changes
          branch: ${{ github.head_ref }}
  windows_job:
    runs-on:  windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cmake 
        run:  mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build && cmake $GITHUB_WORKSPACE  --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -G "Unix Makefiles"
        shell: bash
      - name: nmake
        run: cd $GITHUB_WORKSPACE/build && ls &&  mingw32-make 
        shell: bash
