name: CMake

on:
  push:
    branches: [ chatroom ]
  pull_request:
    branches: [ chatroom ]

jobs:
  runs-on:  ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@master
    - name: cmake 
      run:  mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build && cmake $GITHUB_WORKSPACE  --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug 
      shell: bash
    - name: make
      run: cd $GITHUB_WORKSPACE/build && make
      shell: bash
  runs-on:  windows-latest
    - name: checkout
      uses: actions/checkout@master
    - name: cmake 
      run:  mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build && cmake $GITHUB_WORKSPACE  --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug 
      shell: bash
    - name: make
      run: cd $GITHUB_WORKSPACE/build && make
      shell: bash
